FROM ubuntu
RUN apt update

CMD ["echo" ,"HII"]
# open terminal and write docker build -t ubuntuapp .
# docker run --name myfirstubuntu ubuntuapp
# output HII


# CMD ["whoami"]
# open terminal and write docker build -t ubuntuapp2 .
# docker run --name myfirstubuntu2 ubuntuapp2
# output root 

# cmd ["pwd"]
# output /
